# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: uploader.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'uploader.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0euploader.proto\x12\x08uploader\"\x1a\n\nImageChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\":\n\rUploadSummary\x12\x14\n\x0ctotal_chunks\x18\x01 \x01(\x05\x12\x13\n\x0btotal_bytes\x18\x02 \x01(\x03\x32Q\n\x0fUploaderService\x12>\n\x0bUploadImage\x12\x14.uploader.ImageChunk\x1a\x17.uploader.UploadSummary(\x01\x42\x0eZ\x0c./uploaderpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uploader_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014./uploaderpb'
  _globals['_IMAGECHUNK']._serialized_start=28
  _globals['_IMAGECHUNK']._serialized_end=54
  _globals['_UPLOADSUMMARY']._serialized_start=56
  _globals['_UPLOADSUMMARY']._serialized_end=114
  _globals['_UPLOADERSERVICE']._serialized_start=116
  _globals['_UPLOADERSERVICE']._serialized_end=197
# @@protoc_insertion_point(module_scope)
