// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: uploader.proto

package uploaderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw byte data for a file chunk
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageChunk) Reset() {
	*x = ImageChunk{}
	mi := &file_uploader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageChunk) ProtoMessage() {}

func (x *ImageChunk) ProtoReflect() protoreflect.Message {
	mi := &file_uploader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageChunk.ProtoReflect.Descriptor instead.
func (*ImageChunk) Descriptor() ([]byte, []int) {
	return file_uploader_proto_rawDescGZIP(), []int{0}
}

func (x *ImageChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalChunks   int32                  `protobuf:"varint,1,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSummary) Reset() {
	*x = UploadSummary{}
	mi := &file_uploader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSummary) ProtoMessage() {}

func (x *UploadSummary) ProtoReflect() protoreflect.Message {
	mi := &file_uploader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSummary.ProtoReflect.Descriptor instead.
func (*UploadSummary) Descriptor() ([]byte, []int) {
	return file_uploader_proto_rawDescGZIP(), []int{1}
}

func (x *UploadSummary) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *UploadSummary) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

var File_uploader_proto protoreflect.FileDescriptor

const file_uploader_proto_rawDesc = "" +
	"\n" +
	"\x0euploader.proto\x12\buploader\" \n" +
	"\n" +
	"ImageChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"S\n" +
	"\rUploadSummary\x12!\n" +
	"\ftotal_chunks\x18\x01 \x01(\x05R\vtotalChunks\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x03R\n" +
	"totalBytes2Q\n" +
	"\x0fUploaderService\x12>\n" +
	"\vUploadImage\x12\x14.uploader.ImageChunk\x1a\x17.uploader.UploadSummary(\x01B\x0eZ\f./uploaderpbb\x06proto3"

var (
	file_uploader_proto_rawDescOnce sync.Once
	file_uploader_proto_rawDescData []byte
)

func file_uploader_proto_rawDescGZIP() []byte {
	file_uploader_proto_rawDescOnce.Do(func() {
		file_uploader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_uploader_proto_rawDesc), len(file_uploader_proto_rawDesc)))
	})
	return file_uploader_proto_rawDescData
}

var file_uploader_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_uploader_proto_goTypes = []any{
	(*ImageChunk)(nil),    // 0: uploader.ImageChunk
	(*UploadSummary)(nil), // 1: uploader.UploadSummary
}
var file_uploader_proto_depIdxs = []int32{
	0, // 0: uploader.UploaderService.UploadImage:input_type -> uploader.ImageChunk
	1, // 1: uploader.UploaderService.UploadImage:output_type -> uploader.UploadSummary
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_uploader_proto_init() }
func file_uploader_proto_init() {
	if File_uploader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_uploader_proto_rawDesc), len(file_uploader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_uploader_proto_goTypes,
		DependencyIndexes: file_uploader_proto_depIdxs,
		MessageInfos:      file_uploader_proto_msgTypes,
	}.Build()
	File_uploader_proto = out.File
	file_uploader_proto_goTypes = nil
	file_uploader_proto_depIdxs = nil
}
