// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: uploader.proto

package uploaderpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UploaderService_UploadImage_FullMethodName = "/uploader.UploaderService/UploadImage"
)

// UploaderServiceClient is the client API for UploaderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UploaderServiceClient interface {
	// Defines Client Streaming: The request is a stream of ImageChunk messages.
	UploadImage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImageChunk, UploadSummary], error)
}

type uploaderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUploaderServiceClient(cc grpc.ClientConnInterface) UploaderServiceClient {
	return &uploaderServiceClient{cc}
}

func (c *uploaderServiceClient) UploadImage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImageChunk, UploadSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UploaderService_ServiceDesc.Streams[0], UploaderService_UploadImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImageChunk, UploadSummary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UploaderService_UploadImageClient = grpc.ClientStreamingClient[ImageChunk, UploadSummary]

// UploaderServiceServer is the server API for UploaderService service.
// All implementations must embed UnimplementedUploaderServiceServer
// for forward compatibility.
type UploaderServiceServer interface {
	// Defines Client Streaming: The request is a stream of ImageChunk messages.
	UploadImage(grpc.ClientStreamingServer[ImageChunk, UploadSummary]) error
	mustEmbedUnimplementedUploaderServiceServer()
}

// UnimplementedUploaderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUploaderServiceServer struct{}

func (UnimplementedUploaderServiceServer) UploadImage(grpc.ClientStreamingServer[ImageChunk, UploadSummary]) error {
	return status.Errorf(codes.Unimplemented, "method UploadImage not implemented")
}
func (UnimplementedUploaderServiceServer) mustEmbedUnimplementedUploaderServiceServer() {}
func (UnimplementedUploaderServiceServer) testEmbeddedByValue()                         {}

// UnsafeUploaderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UploaderServiceServer will
// result in compilation errors.
type UnsafeUploaderServiceServer interface {
	mustEmbedUnimplementedUploaderServiceServer()
}

func RegisterUploaderServiceServer(s grpc.ServiceRegistrar, srv UploaderServiceServer) {
	// If the following call pancis, it indicates UnimplementedUploaderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UploaderService_ServiceDesc, srv)
}

func _UploaderService_UploadImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UploaderServiceServer).UploadImage(&grpc.GenericServerStream[ImageChunk, UploadSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UploaderService_UploadImageServer = grpc.ClientStreamingServer[ImageChunk, UploadSummary]

// UploaderService_ServiceDesc is the grpc.ServiceDesc for UploaderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UploaderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "uploader.UploaderService",
	HandlerType: (*UploaderServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadImage",
			Handler:       _UploaderService_UploadImage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "uploader.proto",
}
