# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: storage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstorage.proto\x12\x07storage\"w\n\x0c\x46ileMetadata\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x12\n\nsize_bytes\x18\x03 \x01(\x03\x12\x1c\n\x14storage_node_address\x18\x04 \x01(\t\x12\x12\n\nauth_token\x18\x05 \x01(\t\"O\n\tFileChunk\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63hunk_index\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x0e\n\x06offset\x18\x04 \x01(\x03\"Y\n\x0cUploadStatus\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x16\n\x0e\x62ytes_received\x18\x02 \x01(\x03\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x0f\n\x07message\x18\x04 \x01(\t\"\x07\n\x05\x45mpty2\xc9\x01\n\x0bMetaService\x12=\n\rRequestUpload\x12\x15.storage.FileMetadata\x1a\x15.storage.FileMetadata\x12?\n\x0fGetFileLocation\x12\x15.storage.FileMetadata\x1a\x15.storage.FileMetadata\x12:\n\x0fGetSystemStatus\x12\x0e.storage.Empty\x1a\x15.storage.FileMetadata0\x01\x32G\n\x0b\x46ileService\x12\x38\n\nStreamFile\x12\x12.storage.FileChunk\x1a\x12.storage.FileChunk(\x01\x30\x01\x42\rZ\x0b./storagepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013./storagepb'
  _globals['_FILEMETADATA']._serialized_start=26
  _globals['_FILEMETADATA']._serialized_end=145
  _globals['_FILECHUNK']._serialized_start=147
  _globals['_FILECHUNK']._serialized_end=226
  _globals['_UPLOADSTATUS']._serialized_start=228
  _globals['_UPLOADSTATUS']._serialized_end=317
  _globals['_EMPTY']._serialized_start=319
  _globals['_EMPTY']._serialized_end=326
  _globals['_METASERVICE']._serialized_start=329
  _globals['_METASERVICE']._serialized_end=530
  _globals['_FILESERVICE']._serialized_start=532
  _globals['_FILESERVICE']._serialized_end=603
# @@protoc_insertion_point(module_scope)
