# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import storage_pb2 as storage__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in storage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MetaServiceStub(object):
    """=== Service 1: MetaService (Unary/Server Streaming) ===
    Handled by the Master Node (Go)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestUpload = channel.unary_unary(
                '/storage.MetaService/RequestUpload',
                request_serializer=storage__pb2.FileMetadata.SerializeToString,
                response_deserializer=storage__pb2.FileMetadata.FromString,
                _registered_method=True)
        self.GetFileLocation = channel.unary_unary(
                '/storage.MetaService/GetFileLocation',
                request_serializer=storage__pb2.FileMetadata.SerializeToString,
                response_deserializer=storage__pb2.FileMetadata.FromString,
                _registered_method=True)
        self.GetSystemStatus = channel.unary_stream(
                '/storage.MetaService/GetSystemStatus',
                request_serializer=storage__pb2.Empty.SerializeToString,
                response_deserializer=storage__pb2.FileMetadata.FromString,
                _registered_method=True)


class MetaServiceServicer(object):
    """=== Service 1: MetaService (Unary/Server Streaming) ===
    Handled by the Master Node (Go)
    """

    def RequestUpload(self, request, context):
        """Unary: Client registers the intent to upload a file. Master assigns storage and token.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileLocation(self, request, context):
        """Unary: Client queries the Master for a file's location to download it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemStatus(self, request, context):
        """Server Streaming: Get status of all files (for admin/monitoring).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestUpload,
                    request_deserializer=storage__pb2.FileMetadata.FromString,
                    response_serializer=storage__pb2.FileMetadata.SerializeToString,
            ),
            'GetFileLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileLocation,
                    request_deserializer=storage__pb2.FileMetadata.FromString,
                    response_serializer=storage__pb2.FileMetadata.SerializeToString,
            ),
            'GetSystemStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSystemStatus,
                    request_deserializer=storage__pb2.Empty.FromString,
                    response_serializer=storage__pb2.FileMetadata.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'storage.MetaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('storage.MetaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MetaService(object):
    """=== Service 1: MetaService (Unary/Server Streaming) ===
    Handled by the Master Node (Go)
    """

    @staticmethod
    def RequestUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.MetaService/RequestUpload',
            storage__pb2.FileMetadata.SerializeToString,
            storage__pb2.FileMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFileLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.MetaService/GetFileLocation',
            storage__pb2.FileMetadata.SerializeToString,
            storage__pb2.FileMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/storage.MetaService/GetSystemStatus',
            storage__pb2.Empty.SerializeToString,
            storage__pb2.FileMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FileServiceStub(object):
    """=== Service 2: FileService (Bidirectional Streaming) ===
    Handled by the Storage Node (Go)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamFile = channel.stream_stream(
                '/storage.FileService/StreamFile',
                request_serializer=storage__pb2.FileChunk.SerializeToString,
                response_deserializer=storage__pb2.FileChunk.FromString,
                _registered_method=True)


class FileServiceServicer(object):
    """=== Service 2: FileService (Bidirectional Streaming) ===
    Handled by the Storage Node (Go)
    """

    def StreamFile(self, request_iterator, context):
        """Bidirectional Stream: Handles both upload (client stream) and download (server stream)
        in a single session, allowing for control messages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamFile': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamFile,
                    request_deserializer=storage__pb2.FileChunk.FromString,
                    response_serializer=storage__pb2.FileChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'storage.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('storage.FileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """=== Service 2: FileService (Bidirectional Streaming) ===
    Handled by the Storage Node (Go)
    """

    @staticmethod
    def StreamFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/storage.FileService/StreamFile',
            storage__pb2.FileChunk.SerializeToString,
            storage__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
