# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ticker_pb2 as ticker__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ticker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TickerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStockPrices = channel.unary_stream(
                '/ticker.TickerService/GetStockPrices',
                request_serializer=ticker__pb2.TickerRequest.SerializeToString,
                response_deserializer=ticker__pb2.StockPrice.FromString,
                _registered_method=True)


class TickerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStockPrices(self, request, context):
        """Defines Server Streaming: The response is a stream of StockPrice messages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TickerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStockPrices': grpc.unary_stream_rpc_method_handler(
                    servicer.GetStockPrices,
                    request_deserializer=ticker__pb2.TickerRequest.FromString,
                    response_serializer=ticker__pb2.StockPrice.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ticker.TickerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ticker.TickerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TickerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStockPrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ticker.TickerService/GetStockPrices',
            ticker__pb2.TickerRequest.SerializeToString,
            ticker__pb2.StockPrice.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
